### ISSUE TITLE
Erro ao carregar certificado A1

### ISSUE THREAD

**Issue by victorschiling** [Samuel-Oliveira/Java_Certificado#17]
Estou tendo a seguinte stack trace ao carregar um cerficado A1:

`java.lang.ClassCastException: class org.bouncycastle.asn1.DERPrintableString cannot be cast to class org.bouncycastle.asn1.ASN1TaggedObject (org.bouncycastle.asn1.DERPrintableString and org.bouncycastle.asn1.ASN1TaggedObject are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @140d1230)
	at br.com.swconsultoria.certificado.CertificadoService.lambda$null$9(CertificadoService.java:398)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at br.com.swconsultoria.certificado.CertificadoService.lambda$getDocumentoFromCertificado$10(CertificadoService.java:390)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at br.com.swconsultoria.certificado.CertificadoService.getDocumentoFromCertificado(CertificadoService.java:389)
	at br.com.swconsultoria.certificado.CertificadoService.setDadosCertificado(CertificadoService.java:102)
	at br.com.swconsultoria.certificado.CertificadoService.certificadoPfxBytes(CertificadoService.java:82)`

Alguém já passou por esse problema?

**Comment by rodrigocananea** [comment]
@victorschiling isso me parece um conflito com as versões do bcprov, teria que encontrar qual dependencia está causando o conflito e dar um exclude nela, assim:
```xml
<exclusions>
    <exclusion>
        <artifactId>bcprov-jdk14on</artifactId>
        <groupId>org.bouncycastle</groupId>
    </exclusion>
</exclusions>
```

Se caso precisar mais ajuda com isso pode falar no discord da java brasil com nós lá
https://discord.gg/xRakgqKu5E

**Comment by victorschiling** [comment]
Opa, muito obrigado pela resposta @rodrigocananea ! Vou investigar as dependências do meu projeto e qualquer coisa dou um alô lá no discord.

**Comment by thiagohsp** [comment]
@victorschiling conseguiu resolver? Estou tendo o mesmo problema, vou analisar as dependencias tbm.

**Comment by rodrigocananea** [comment]
@thiagohsp se quiser ajuda nisso pode entrar no discord e criar um post no forum do servidor com seu erro e seu pom.xml que ajudamos a revisar qual dependencia pode ser o problema 

https://discord.gg/xRakgqKu5E
